version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(deps): "
    rebase-strategy: "disabled"
    reviewers:
      - "ghost-road-studio/devs"